# Per environment values which override defaults in hmpps-probation-in-court-prepare-a-case-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: prepare-a-case-ui-dev.apps.live-1.cloud-platform.service.justice.gov.uk

  env:
    INGRESS_URL: "https://prepare-a-case-ui-dev.apps.live-1.cloud-platform.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: "false"
    COURT_CASE_SERVICE_URL: "https://court-case-service-dev.apps.live-1.cloud-platform.service.justice.gov.uk"
    USER_PREFERENCE_SERVICE_URL: "https://hmpps-user-preferences-dev.hmpps.service.justice.gov.uk"
    CASE_SNAPSHOT_TIMES: "00:00,08:45,09:45,10:15,10:45,11:15,11:45,12:15,12:45,13:15,13:45,14:15,14:45,15:15,15:45,16:15,16:45,17:15,17:45"
    CASES_PER_PAGE: 20
    ENABLE_PAST_CASES_NAVIGATION: true
    ENABLE_CASE_COMMENTS: true
    ENABLE_CASE_PROGRESS: true
    ENABLE_APP_INSIGHTS: true
    ENABLE_HEARING_OUTCOMES: true
    ENABLE_WORKFLOW: true
    CASE_SEARCH_USERS: all
    ENABLE_MOVE_TO_RESULTED_ACTION: true
    DEFAULT_TIMEOUT: 12500
    ENABLE_MATCHER_LOGGING: true
    ENABLE_CLICK_ANALYTICS: true

generic-prometheus-alerts:
  alertSeverity: slack-probation_in_court_alerts_preprod
