---
# Per environment values which override defaults in hmpps-probation-in-court-prepare-a-case-ui/values.yaml

generic-service:
  ingress:
    host: probation-in-court-prepare-a-case-ui.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://probation-in-court-prepare-a-case-ui.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    EXAMPLE_API_URL: 'https://template-kotlin.hmpps.service.justice.gov.uk'
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: slack-probation_in_court_alerts_prod
